from fastapi import APIRouter
from pydantic import BaseModel, Field
from toolbox import methods
from dotenv import load_dotenv
import os
import json
from typing import List
from datetime import datetime
import traceback
# from debug2 import debug2 as dbg

load_dotenv()

script_name = os.path.basename(__file__)
router = APIRouter()
SUPPORTED_LINEAGE_SOURCE_EXTENSIONS = {".txt", ".xml", ".log", ".sql"}


def _normalize_drawio_payload(payload):
    """
    Convert MCP/tool string payloads into raw XML or diagram bundles.
    """

    normalized = payload

    if isinstance(normalized, str):
        stripped = normalized.strip()

        if stripped.startswith("<mxfile") and '\\"' in stripped:
            normalized = (
                stripped
                .replace("\\r\\n", "\n")
                .replace("\\n", "\n")
                .replace('\\"', '"')
            )

    for _ in range(2):
        if not isinstance(normalized, str):
            break

        stripped = normalized.strip()

        if not stripped:
            return ""

        if stripped.startswith(("<mxfile", "{", "[")):
            break

        try:
            decoded = json.loads(stripped)
        except Exception:
            break

        if decoded == normalized:
            break

        normalized = decoded

    return normalized


# ==========================================================
# Request Models
# ==========================================================


class AvailableLineageSources(BaseModel):
    """List the pseudocode files that are valid inputs for a lineage run."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")


class ReadLineageSources(BaseModel):
    """Read the chosen pseudocode files and lock the source-file scope for this run."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    job_files: List[str] = Field(..., description="List of pseudocode ETL job files to be used as lineage input.")


class LineageOptions(BaseModel):
    """Control the lineage abstraction, SQL visibility, lookup visibility, and optional LLM semantic enrichment."""
    diagram_mode: str = Field(
        "logical",
        description="Diagram abstraction level. Use 'logical' for a clean business-readable lineage or 'technical' for a more detailed graph."
    )
    include_sql_sources: bool = Field(
        False,
        description="Whether SQL source tables extracted from embedded SQL should be shown as visible lineage nodes."
    )
    collapse_intermediate_datasets: bool = Field(
        True,
        description="Whether anonymous transport datasets such as dataset_1 or dataset_17 should be collapsed into direct stage-to-stage relationships."
    )
    include_lookup_nodes: bool = Field(
        True,
        description="Whether lookup or hashed-file helper stages should remain visible in the final logical lineage."
    )
    llm_role_classification: bool = Field(
        False,
        description="Whether LLM-assisted stage-role classification should be used to refine SOURCE, LOOKUP, TRANSFORM, STORE, DECISION, or TARGET semantics before final normalization."
    )
    llm_business_labels: bool = Field(
        False,
        description="Whether LLM-assisted business-readable labels should be generated in addition to preserving original stage and table names."
    )
    llm_sql_grouping: bool = Field(
        False,
        description="Whether LLM-assisted SQL table grouping should be used to group staging, dimension, fact, or reference tables into clearer upstream source views."
    )


class DetectJobBoundaries(BaseModel):
    """Split selected pseudocode into independent jobs or pipelines and tag the parser family."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    lineage_source_file: str = Field(None, description="Lineage source file generated by 'read_lineage_sources' tool.")


class ParseETLStages(BaseModel):
    """Extract structured stage metadata through the parser matched to each pseudocode family, with targeted ambiguity resolution where needed."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    job_boundaries_file: str = Field(None, description="Job boundary file generated by 'detect_job_boundaries' tool.")


class ExtractDatasetLinks(BaseModel):
    """Resolve producer-consumer relationships between parsed ETL stages."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    parsed_stage_file: str = Field(None, description="Parsed stage metadata file generated by 'parse_etl_stages' tool.")


class ExtractSQLMetadata(BaseModel):
    """Extract upstream SQL table references from SQL-bearing stages."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    parsed_stage_file: str = Field(None, description="Parsed stage metadata file generated by 'parse_etl_stages' tool.")


class NormalizeLineageGraph(BaseModel):
    """Convert parsed stage relationships into the semantic graph that should appear in the final diagram."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    dataset_links_file: str = Field(None, description="Dataset relationship file generated by 'extract_dataset_links' tool.")
    sql_metadata_file: str = Field(None, description="SQL metadata file generated by 'extract_sql_metadata' tool.")
    options: LineageOptions = Field(
        default_factory=LineageOptions,
        description="Lineage rendering options that instruct normalization how much detail to preserve in the final graph."
    )


class BuildLineageGraph(BaseModel):
    """Finalize the graph structure that will be given to the layout engine."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    normalized_graph_file: str = Field(None, description="Normalized lineage graph file generated by 'normalize_lineage_graph' tool.")


class GenerateLayout(BaseModel):
    """Assign deterministic coordinates to the finalized lineage graph."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    lineage_graph_file: str = Field(None, description="Lineage graph JSON file generated by 'build_lineage_graph' tool.")


class GenerateDrawioXML(BaseModel):
    """Render the positioned lineage graph into draw.io XML without changing lineage semantics."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    layout_file: str = Field(None, description="Layout JSON file generated by 'generate_layout' tool.")


class StoreLineageDiagram(BaseModel):
    """Persist the generated draw.io XML as the final lineage artifact."""
    user_id: str = Field("user2", description="The unique user id of a specific user (default: 'user2').")
    drawio_xml: str = Field(..., description="Generated draw.io XML diagram.")
    diagram_filename: str = Field(
        None,
        description="Optional filename used for storing lineage diagram. If omitted, a deterministic filename is derived from the selected source files and active lineage options so reruns overwrite the same output."
    )


# ==========================================================
# Tools
# ==========================================================


@router.post(
    "/available_lineage_sources",
    operation_id="available_lineage_sources",
    summary="Returns ETL pseudocode files available for lineage generation",
    description="Scans lineage source directory and returns ETL pseudocode files available for lineage analysis."
)
async def available_lineage_sources(p_body: AvailableLineageSources):
    """
    Retrieve ETL pseudocode files available for lineage processing.

    This endpoint scans the lineage source directory associated with the user
    and returns pseudocode files that can be used as input for lineage extraction.

    These files typically contain ETL job pseudocode exported from ETL tools
    such as DataStage or similar systems.

    LLM usage guidance:
        - Call this first whenever file scope is unknown.
        - Use only filenames returned by this tool.
        - If exactly one relevant file is available and the user wants lineage generation, that file can usually be selected directly.

    Args:
        p_body (AvailableLineageSources):
            user_id (str): Unique identifier for the user.

    Returns:
        dict:
            Available_Lineage_Sources (List[str]): List of available ETL pseudocode files.
            error (str, optional): Error message if retrieval fails.
    """

    try:

        log_file = methods.get_or_create_file(
            agent_name="lineage_agent",
            tool_name="available_lineage_sources"
        )
        # log_file = None
        
        execution_id = datetime.now().strftime('%Y-%m-%d-%H-%M-%S')

        lineage_dir = methods.get_lineage_upload_dir(p_body.user_id, "sources")
        os.makedirs(lineage_dir, exist_ok=True)
        files = [
            filename for filename in methods.list_files_in_directory(lineage_dir)
            if os.path.splitext(filename)[1].lower() in SUPPORTED_LINEAGE_SOURCE_EXTENSIONS
        ]

        # dbg.dprint2(script_name, execution_id, "status", "Lineage sources fetched", log_file)

        return {"Available_Lineage_Sources": files}

    except Exception as e:
        tb = traceback.format_exc()
        print(tb)
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/read_lineage_sources",
    operation_id="read_lineage_sources",
    summary="Read ETL pseudocode files",
    description="Reads ETL pseudocode files and consolidates them into a lineage source JSON artifact."
)
async def read_lineage_sources(p_body: ReadLineageSources):
    """
    Load pseudocode ETL job files.

    This endpoint reads one or more pseudocode ETL job files and consolidates them
    into a structured lineage source JSON file used by downstream lineage tools.

    The selected filenames also become the canonical lineage scope for this run.
    Later tools should continue to reuse artifacts derived from this same source set.

    LLM usage guidance:
        - Call this immediately after file selection.
        - The chosen files define the lineage scope and later deterministic output naming.
        - Do not skip this step even if the user already named the file in plain text.

    Returns:
        dict:
            Lineage_Source_File (str): Generated lineage source file.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        filename = f"{execution_id}_lineage_sources.json"

        source_dir = methods.get_lineage_upload_dir(p_body.user_id, "sources")

        os.makedirs(source_dir, exist_ok=True)

        file_path = os.path.join(source_dir, filename)

        # job_paths = [
        #     os.path.join(source_dir, f)
        #     for f in p_body.job_files
        # ]
        job_paths = []
        for f in p_body.job_files:
            full_path = os.path.join(source_dir, f)
 
            if not os.path.exists(full_path):
                return {"error": f"File not found: {f}"}
 
            job_paths.append(full_path)

        methods.read_etl_sources(job_paths, file_path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "source_file": filename,
                "source_files": p_body.job_files,
                "job_boundaries_file": None,
                "parsed_stage_file": None,
                "dataset_links_file": None,
                "sql_metadata_file": None,
                "normalized_graph_file": None,
                "lineage_graph_file": None,
                "layout_file": None,
                "lineage_options": None
            }
        )

        return {"Lineage_Source_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/detect_job_boundaries",
    operation_id="detect_job_boundaries",
    summary="Detect ETL pipeline boundaries",
    description="Identifies independent ETL pipelines within pseudocode files."
)
async def detect_job_boundaries(p_body: DetectJobBoundaries):
    """
    Detect job boundaries within pseudocode.

    ETL pseudocode files may contain multiple independent ETL pipelines.
    This tool detects boundaries separating each pipeline to ensure lineage
    graphs are constructed accurately.
    It also tags each job with the parser family that should be used downstream.

    If a lineage source file is not explicitly provided,
    the tool automatically retrieves the most recent source file from lineage state.

    LLM usage guidance:
        - Call this after `read_lineage_sources`.
        - Use it even for a single pseudocode file because one file may contain multiple jobs.
        - The backend may keep the full file as one job for parser families such as Informatica or Alteryx.

    Returns:
        dict:
            Job_Boundaries_File (str): JSON file containing detected job boundaries.
            Detected_Parser_Families (List[str]): Parser families detected across the selected inputs.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.lineage_source_file or methods.get_previous_state(p_body.user_id, "source_file")

        filename = f"{execution_id}_job_boundaries.json"

        job_dir = methods.get_lineage_upload_dir(p_body.user_id, "jobs")

        os.makedirs(job_dir, exist_ok=True)

        file_path = os.path.join(job_dir, filename)

        source_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "sources",
            input_file,
            base_type="upload"
        )

        methods.detect_job_boundaries(source_path, file_path)
        jobs = methods.read_json(file_path)
        parser_families = sorted({item.get("parser_type", "datastage") for item in jobs if isinstance(item, dict)})

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "job_boundaries_file": filename,
                "parsed_stage_file": None,
                "dataset_links_file": None,
                "sql_metadata_file": None,
                "normalized_graph_file": None,
                "lineage_graph_file": None,
                "layout_file": None,
                "lineage_options": None
            }
        )

        return {
            "Job_Boundaries_File": filename,
            "Detected_Parser_Families": parser_families,
        }

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/parse_etl_stages",
    operation_id="parse_etl_stages",
    summary="Parse ETL stages from pseudocode",
    description="Extracts stage metadata from ETL pseudocode."
)
async def parse_etl_stages(p_body: ParseETLStages):
    """
    Parse ETL stages.

    This endpoint parses ETL pseudocode and extracts stage-level metadata
    including stage names, types, input links, output links, and SQL logic.
    The backend auto-detects the pseudocode family and routes each job through
    the matching tool-specific parser before normalizing into one canonical stage shape.
    For connector-less Alteryx pseudocode, the backend may run a targeted ambiguity-resolution pass
    on generic tools such as Formula, Filter, Sort, or AutoField when direct wiring is incomplete.

    LLM usage guidance:
        - Call this after `detect_job_boundaries`.
        - This is the step that exposes stage names, stage kinds, links, and SQL text for downstream reasoning.
        - The returned stage metadata is canonical even when the source syntax differs across DataStage, Informatica, or Alteryx.
        - For Alteryx, ambiguous generic tools may be connected by a validated backend inference pass before the stage artifact is written.

    Returns:
        dict:
            Parsed_Stage_File (str): JSON file containing parsed stage metadata.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.job_boundaries_file or methods.get_previous_state(p_body.user_id, "job_boundaries_file")

        filename = f"{execution_id}_parsed_stages.json"

        parse_dir = methods.get_lineage_upload_dir(p_body.user_id, "parsed")

        os.makedirs(parse_dir, exist_ok=True)

        file_path = os.path.join(parse_dir, filename)

        job_boundaries_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "jobs",
            input_file,
            base_type="upload"
        )

        methods.parse_stages_chunked(job_boundaries_path, file_path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "parsed_stage_file": filename,
                "dataset_links_file": None,
                "sql_metadata_file": None,
                "normalized_graph_file": None,
                "lineage_graph_file": None,
                "layout_file": None,
                "lineage_options": None
            }
        )

        return {"Parsed_Stage_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/extract_dataset_links",
    operation_id="extract_dataset_links",
    summary="Extract dataset relationships",
    description="Identifies dataset flows between ETL stages."
)
async def extract_dataset_links(p_body: ExtractDatasetLinks):
    """
    Extract dataset relationships.

    This endpoint analyzes parsed ETL stages and identifies relationships
    between datasets flowing through transformations.

    LLM usage guidance:
        - Call this after `parse_etl_stages`.
        - It converts parsed stage links into graph-ready producer-consumer relationships.
        - When multiple source files were selected, the backend keeps relationships grouped by source file.

    Example relationship:

        dataset_A → Transformer → dataset_B

    Returns:
        dict:
            Dataset_Links_File (str): JSON file containing dataset relationships.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.parsed_stage_file or methods.get_previous_state(p_body.user_id, "parsed_stage_file")

        filename = f"{execution_id}_dataset_links.json"

        dataset_dir = methods.get_lineage_upload_dir(p_body.user_id, "datasets")

        os.makedirs(dataset_dir, exist_ok=True)

        path = os.path.join(dataset_dir, filename)

        parsed_stage_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "parsed",
            input_file,
            base_type="upload"
        )

        methods.extract_dataset_links(parsed_stage_path, path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "dataset_links_file": filename,
                "normalized_graph_file": None,
                "lineage_graph_file": None,
                "layout_file": None
            }
        )

        return {"Dataset_Links_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/extract_sql_metadata",
    operation_id="extract_sql_metadata",
    summary="Extract SQL metadata",
    description="Extract database tables referenced inside SQL transformations."
)
async def extract_sql_metadata(p_body: ExtractSQLMetadata):
    """
    Extract SQL metadata.

    This endpoint scans SQL blocks embedded inside ETL transformation stages
    and extracts database tables referenced in the SQL logic.

    LLM usage guidance:
        - Call this whenever parsed stages contain SQL or when upstream database lineage matters.
        - Even for logical diagrams, SQL metadata should be extracted because normalization may decide to surface those tables.
        - When multiple source files are selected, SQL metadata is tracked per source file.

    Returns:
        dict:
            SQL_Metadata_File (str): JSON file containing extracted SQL metadata.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.parsed_stage_file or methods.get_previous_state(p_body.user_id, "parsed_stage_file")

        filename = f"{execution_id}_sql_metadata.json"

        sql_dir = methods.get_lineage_upload_dir(p_body.user_id, "sql")

        os.makedirs(sql_dir, exist_ok=True)

        path = os.path.join(sql_dir, filename)

        parsed_stage_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "parsed",
            input_file,
            base_type="upload"
        )

        methods.extract_sql_metadata(parsed_stage_path, path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "sql_metadata_file": filename,
                "normalized_graph_file": None,
                "lineage_graph_file": None,
                "layout_file": None
            }
        )

        return {"SQL_Metadata_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/normalize_lineage_graph",
    operation_id="normalize_lineage_graph",
    summary="Normalize lineage graph",
    description="Convert raw lineage relationships into structured graph nodes."
)
async def normalize_lineage_graph(p_body: NormalizeLineageGraph):
    """
    Normalize lineage graph.

    Converts extracted dataset links and SQL metadata into structured lineage nodes.

    This is the main abstraction step. The provided options tell the backend
    whether to favor a clean logical lineage or a more detailed technical one.
    The LLM should choose these options deliberately based on the user's intent.

    LLM usage guidance:
        - This is the main output-shaping step of the lineage pipeline.
        - Use `diagram_mode="logical"` for clean, presentation-ready lineage.
        - Use `diagram_mode="technical"` for debugging or physically detailed lineage.
        - Use `collapse_intermediate_datasets=True` to hide transport-only datasets.
        - Use `include_lookup_nodes=True` when lookup stores help explain enrichment or joins.
        - Use `include_sql_sources=True` when visible database lineage is required.
        - Use `llm_role_classification=True` when stage role inference is ambiguous and business semantics matter more than pure stage-type rules.
        - Use `llm_business_labels=True` when the user wants more readable node text without losing the original labels.
        - Use `llm_sql_grouping=True` when many SQL tables should be grouped into staging, fact, dimension, or reference-style source clusters.
        - In logical mode, preserve original stage and table names and append semantic context rather than renaming nodes.
        - In logical mode, the backend may group many source tables into one source node when they all feed the same downstream stage.
        - When multiple source files were selected, normalization is applied independently per source file unless the user explicitly asked for a merged lineage.

    Node categories include:

        SOURCE
        TRANSFORM
        DATASET
        TARGET
        LOOKUP

    Returns:
        dict:
            Normalized_Graph_File (str): JSON file containing normalized graph.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        dataset_file = p_body.dataset_links_file or methods.get_previous_state(p_body.user_id, "dataset_links_file")
        sql_file = p_body.sql_metadata_file or methods.get_previous_state(p_body.user_id, "sql_metadata_file")

        filename = f"{execution_id}_normalized_graph.json"

        graph_dir = methods.get_lineage_upload_dir(p_body.user_id, "normalized")

        os.makedirs(graph_dir, exist_ok=True)

        path = os.path.join(graph_dir, filename)

        dataset_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "datasets",
            dataset_file,
            base_type="upload"
        )
        sql_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "sql",
            sql_file,
            base_type="upload"
        )

        methods.normalize_lineage_graph(
            dataset_path,
            sql_path,
            path,
            p_body.options.model_dump()
        )

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "normalized_graph_file": filename,
                "lineage_options": p_body.options.model_dump(),
                "lineage_graph_file": None,
                "layout_file": None
            }
        )

        return {"Normalized_Graph_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/build_lineage_graph",
    operation_id="build_lineage_graph",
    summary="Build lineage graph",
    description="Construct lineage graph using bottom-up traversal."
)
async def build_lineage_graph(p_body: BuildLineageGraph):
    """
    Build lineage graph.

    Constructs the graph that the layout step will render.

    LLM usage guidance:
        - Call this after `normalize_lineage_graph`.
        - After this step, lineage semantics should already be settled.
        - When multiple source files were selected, this produces one finalized graph per source file.

    Returns:
        dict:
            Lineage_Graph_File (str): JSON file containing final lineage graph.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.normalized_graph_file or methods.get_previous_state(p_body.user_id, "normalized_graph_file")

        filename = f"{execution_id}_lineage_graph.json"

        graph_dir = methods.get_lineage_upload_dir(p_body.user_id, "graph")

        os.makedirs(graph_dir, exist_ok=True)

        path = os.path.join(graph_dir, filename)

        normalized_graph_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "normalized",
            input_file,
            base_type="upload"
        )

        methods.build_lineage_graph_bottom_up(normalized_graph_path, path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {
                "lineage_graph_file": filename,
                "layout_file": None
            }
        )

        return {"Lineage_Graph_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/generate_layout",
    operation_id="generate_layout",
    summary="Generate diagram layout",
    description="Assign spatial coordinates to lineage graph nodes."
)
async def generate_layout(p_body: GenerateLayout):
    """
    Generate diagram layout.

    Assigns spatial coordinates to lineage nodes for visualization.

    LLM usage guidance:
        - Call this after `build_lineage_graph`.
        - This step positions nodes; it should not be treated as semantic inference.
        - This step requires Graphviz to be installed in the runtime environment.
        - If Graphviz is missing or misconfigured, layout generation fails instead of falling back to a custom layout engine.

    Returns:
        dict:
            Layout_File (str): JSON file containing node coordinates.
    """

    try:

        execution_id = datetime.now().strftime('%Y%m%d%H%M%S')

        input_file = p_body.lineage_graph_file or methods.get_previous_state(p_body.user_id, "lineage_graph_file")

        filename = f"{execution_id}_layout.json"

        layout_dir = methods.get_lineage_upload_dir(p_body.user_id, "layout")

        os.makedirs(layout_dir, exist_ok=True)

        path = os.path.join(layout_dir, filename)

        lineage_graph_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "graph",
            input_file,
            base_type="upload"
        )

        methods.generate_layout(lineage_graph_path, path)

        methods.save_lineage_state(
            execution_id,
            p_body.user_id,
            {"layout_file": filename}
        )

        return {"Layout_File": filename}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/generate_drawio_xml",
    operation_id="generate_drawio_xml",
    summary="Generate draw.io XML diagram",
    description="Convert lineage layout into draw.io XML format."
)
async def generate_drawio_xml(p_body: GenerateDrawioXML):
    """
    Generate draw.io XML diagram.

    Converts lineage graph layout into draw.io compatible XML
    so lineage diagrams can be visualized.

    The XML produced here should reflect the abstraction choices already made
    earlier in normalization and graph construction. The LLM should not expect
    this tool to reinterpret lineage semantics from scratch.

    LLM usage guidance:
        - Call this only after layout generation.
        - If the graph is semantically wrong, fix upstream normalization or graph building rather than this renderer.
        - Node labels preserve original names and may append short semantic context such as source, transform, conditional, or final target.
        - When multiple source files were selected, this tool may return multiple draw.io XML payloads bundled together.
        - This tool is responsible for producing the final draw.io-ready lineage representation, not for re-deciding lineage semantics.

    Returns:
        dict:
            Drawio_XML (str): Generated XML diagram.
    """

    try:

        input_file = p_body.layout_file or methods.get_previous_state(p_body.user_id, "layout_file")

        layout_path = methods.resolve_lineage_artifact(
            p_body.user_id,
            "layout",
            input_file,
            base_type="upload"
        )

        xml = methods.generate_drawio_xml(layout_path)

        return {"Drawio_XML": xml}

    except Exception as e:
        return {"error": str(e)}


# ----------------------------------------------------------


@router.post(
    "/store_lineage_diagram",
    operation_id="store_lineage_diagram",
    summary="Store lineage diagram",
    description="Store generated draw.io XML lineage diagram."
)
async def store_lineage_diagram(p_body: StoreLineageDiagram):
    """
    Store lineage diagram.

    Saves generated draw.io XML diagram into lineage output directory.

    If no filename is supplied, this endpoint builds a deterministic filename
    from the selected source files and active lineage options. That behavior
    ensures rerunning the same lineage request overwrites the previous diagram
    instead of creating a new unrelated file.

    LLM usage guidance:
        - Call this after `generate_drawio_xml`.
        - Prefer omitting `diagram_filename` unless the user explicitly asked for a custom file name.
        - If multiple source files were selected, this tool stores one output file per source file by default.
        - Always report the stored filename or filenames back to the user in the final response.

    Returns:
        dict:
            diagram_filename (str): Stored lineage diagram filename.
    """

    try:
        normalized_payload = _normalize_drawio_payload(p_body.drawio_xml)
        parsed_payload = normalized_payload if isinstance(normalized_payload, (dict, list)) else None

        if isinstance(parsed_payload, dict) and isinstance(parsed_payload.get("diagrams"), list):
            stored_files = []
            lineage_options = methods.get_previous_state(p_body.user_id, "lineage_options") or {}
            output_dir = methods.get_lineage_output_dir(p_body.user_id, "diagrams")
            os.makedirs(output_dir, exist_ok=True)

            for diagram in parsed_payload["diagrams"]:
                source_file = diagram.get("source_file") or "lineage"
                xml = _normalize_drawio_payload(diagram.get("drawio_xml", ""))
                diagram_filename = methods.build_lineage_diagram_filename(
                    [source_file],
                    lineage_options,
                    extension=".drawio"
                )
                methods.store_lineage_xml(
                    xml,
                    output_dir,
                    diagram_filename
                )
                stored_files.append(diagram_filename)

            return {"diagram_filenames": stored_files}

        if not p_body.diagram_filename:
            source_files = methods.get_previous_state(p_body.user_id, "source_files") or []
            lineage_options = methods.get_previous_state(p_body.user_id, "lineage_options") or {}
            p_body.diagram_filename = methods.build_lineage_diagram_filename(
                source_files,
                lineage_options,
                extension=".drawio"
            )

        output_dir = methods.get_lineage_output_dir(p_body.user_id, "diagrams")

        os.makedirs(output_dir, exist_ok=True)

        methods.store_lineage_xml(
            normalized_payload if isinstance(normalized_payload, str) else json.dumps(normalized_payload),
            output_dir,
            p_body.diagram_filename
        )

        return {"diagram_filename": p_body.diagram_filename}

    except Exception as e:
        return {"error": str(e)}
