-- =====================================================
-- Auto-generated 3NF Normalized Database Schema
-- Generated by: Automated 3NF Data Modeling System
-- =====================================================

-- Drop existing tables (if any)
-- Execute these statements if you need to recreate the schema

-- DROP TABLE col_50_atm_transactions_t_202e CASCADE CONSTRAINTS;
-- DROP TABLE col_50_atm_transactions CASCADE CONSTRAINTS;
-- DROP TABLE col_49_securities_holdings CASCADE CONSTRAINTS;
-- DROP TABLE col_48_investment_portfolios CASCADE CONSTRAINTS;
-- DROP TABLE col_47_credit_card_transa_a060 CASCADE CONSTRAINTS;
-- DROP TABLE col_47_credit_card_transa_c098 CASCADE CONSTRAINTS;
-- DROP TABLE col_46_credit_cards CASCADE CONSTRAINTS;
-- DROP TABLE col_45_loan_payments CASCADE CONSTRAINTS;
-- DROP TABLE col_44_loans CASCADE CONSTRAINTS;
-- DROP TABLE col_43_transactions_trans_a5b3 CASCADE CONSTRAINTS;
-- DROP TABLE col_43_transactions CASCADE CONSTRAINTS;
-- DROP TABLE col_42_bank_accounts CASCADE CONSTRAINTS;
-- DROP TABLE col_41_bank_customers CASCADE CONSTRAINTS;
-- DROP TABLE col_40_book_checkouts CASCADE CONSTRAINTS;
-- DROP TABLE col_39_library_books CASCADE CONSTRAINTS;
-- DROP TABLE col_38_attendance CASCADE CONSTRAINTS;
-- DROP TABLE col_37_class_schedules_en_4ea6 CASCADE CONSTRAINTS;
-- DROP TABLE col_37_class_schedules_st_210d CASCADE CONSTRAINTS;
-- DROP TABLE col_37_class_schedules CASCADE CONSTRAINTS;
-- DROP TABLE col_36_classrooms CASCADE CONSTRAINTS;
-- DROP TABLE col_35_faculty CASCADE CONSTRAINTS;
-- DROP TABLE col_34_grades CASCADE CONSTRAINTS;
-- DROP TABLE col_33_course_enrollments CASCADE CONSTRAINTS;
-- DROP TABLE col_32_courses CASCADE CONSTRAINTS;
-- DROP TABLE col_31_students CASCADE CONSTRAINTS;
-- DROP TABLE col_30_hospital_departments CASCADE CONSTRAINTS;
-- DROP TABLE col_29_billing CASCADE CONSTRAINTS;
-- DROP TABLE col_28_medical_history CASCADE CONSTRAINTS;
-- DROP TABLE col_27_treatments CASCADE CONSTRAINTS;
-- DROP TABLE col_26_diagnoses CASCADE CONSTRAINTS;
-- DROP TABLE col_25_lab_tests CASCADE CONSTRAINTS;
-- DROP TABLE col_24_prescriptions CASCADE CONSTRAINTS;
-- DROP TABLE col_23_appointments_appoi_13ed CASCADE CONSTRAINTS;
-- DROP TABLE col_23_appointments CASCADE CONSTRAINTS;
-- DROP TABLE col_22_doctors CASCADE CONSTRAINTS;
-- DROP TABLE col_21_patients CASCADE CONSTRAINTS;
-- DROP TABLE col_20_employee_benefits CASCADE CONSTRAINTS;
-- DROP TABLE col_19_training_enrollments CASCADE CONSTRAINTS;
-- DROP TABLE col_18_training_courses CASCADE CONSTRAINTS;
-- DROP TABLE col_17_performance_reviews CASCADE CONSTRAINTS;
-- DROP TABLE col_16_departments CASCADE CONSTRAINTS;
-- DROP TABLE col_15_timesheets CASCADE CONSTRAINTS;
-- DROP TABLE col_14_project_assignments CASCADE CONSTRAINTS;
-- DROP TABLE col_13_projects CASCADE CONSTRAINTS;
-- DROP TABLE col_12_employee_skills CASCADE CONSTRAINTS;
-- DROP TABLE col_11_employees CASCADE CONSTRAINTS;
-- DROP TABLE col_10_categories_category_id CASCADE CONSTRAINTS;
-- DROP TABLE col_10_categories CASCADE CONSTRAINTS;
-- DROP TABLE col_09_payments CASCADE CONSTRAINTS;
-- DROP TABLE col_08_shipping CASCADE CONSTRAINTS;
-- DROP TABLE col_07_promotions_product_ids CASCADE CONSTRAINTS;
-- DROP TABLE col_07_promotions CASCADE CONSTRAINTS;
-- DROP TABLE col_06_inventory CASCADE CONSTRAINTS;
-- DROP TABLE col_05_reviews CASCADE CONSTRAINTS;
-- DROP TABLE col_04_customers CASCADE CONSTRAINTS;
-- DROP TABLE col_03_order_items CASCADE CONSTRAINTS;
-- DROP TABLE col_02_orders CASCADE CONSTRAINTS;
-- DROP TABLE col_01_products_tags CASCADE CONSTRAINTS;
-- DROP TABLE col_01_products CASCADE CONSTRAINTS;

-- =====================================================
-- CREATE TABLE statements
-- =====================================================

-- Table: 01_products
-- Rows: 100
CREATE TABLE col_01_products (
    product_id VARCHAR2(7) NOT NULL,
    product_name VARCHAR2(16) NOT NULL,
    category_id VARCHAR2(7) NOT NULL,
    category_name VARCHAR2(16) NOT NULL,
    supplier_id VARCHAR2(9) NOT NULL,
    supplier_name VARCHAR2(16) NOT NULL,
    supplier_city VARCHAR2(16) NOT NULL,
    price NUMBER(15,2) NOT NULL,
    stock NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_01_products PRIMARY KEY (product_id)
);

-- Table: 01_products_tags
-- Rows: 200
CREATE TABLE col_01_products_tags (
    col_01_products_tags_id NUMBER(10) NOT NULL,
    product_id VARCHAR2(7) NOT NULL,
    tags_value VARCHAR2(10) NOT NULL,
    CONSTRAINT pk_col_01_products_tags PRIMARY KEY (product_id)
);

-- Table: 02_orders
-- Rows: 200
CREATE TABLE col_02_orders (
    order_id VARCHAR2(12) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    customer_name VARCHAR2(16) NOT NULL,
    customer_email VARCHAR2(33) NOT NULL,
    customer_city VARCHAR2(10) NOT NULL,
    order_date DATE NOT NULL,
    status_id NUMBER(10) NOT NULL,
    status_name VARCHAR2(15) NOT NULL,
    total_amount NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_02_orders PRIMARY KEY (order_id)
);

-- Table: 03_order_items
-- Rows: 611
CREATE TABLE col_03_order_items (
    order_item_id VARCHAR2(12) NOT NULL,
    order_id VARCHAR2(12) NOT NULL,
    product_id VARCHAR2(7) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    unit_price NUMBER(15,2) NOT NULL,
    discount NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_03_order_items PRIMARY KEY (order_item_id)
);

-- Table: 04_customers
-- Rows: 100
CREATE TABLE col_04_customers (
    customer_id VARCHAR2(12) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    address_id VARCHAR2(10) NOT NULL,
    street VARCHAR2(18) NOT NULL,
    city VARCHAR2(16) NOT NULL,
    state VARCHAR2(3) NOT NULL,
    zip NUMBER(10) NOT NULL,
    country VARCHAR2(4) NOT NULL,
    CONSTRAINT pk_col_04_customers PRIMARY KEY (customer_id)
);

-- Table: 05_reviews
-- Rows: 300
CREATE TABLE col_05_reviews (
    review_id VARCHAR2(12) NOT NULL,
    product_id VARCHAR2(7) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    rating NUMBER(10) NOT NULL,
    review_text VARCHAR2(22) NOT NULL,
    review_date DATE NOT NULL,
    helpful_count NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_05_reviews PRIMARY KEY (review_id)
);

-- Table: 06_inventory
-- Rows: 150
CREATE TABLE col_06_inventory (
    inventory_id VARCHAR2(12) NOT NULL,
    product_id VARCHAR2(7) NOT NULL,
    warehouse_id VARCHAR2(6) NOT NULL,
    warehouse_name VARCHAR2(16) NOT NULL,
    warehouse_city VARCHAR2(12) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    last_updated DATE NOT NULL,
    CONSTRAINT pk_col_06_inventory PRIMARY KEY (inventory_id)
);

-- Table: 07_promotions
-- Rows: 30
CREATE TABLE col_07_promotions (
    promotion_id VARCHAR2(12) NOT NULL,
    promotion_name VARCHAR2(18) NOT NULL,
    discount_percent NUMBER(15,2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    CONSTRAINT pk_col_07_promotions PRIMARY KEY (promotion_id)
);

-- Table: 07_promotions_product_ids
-- Rows: 167
CREATE TABLE col_07_promotions_product_ids (
    col_07_promotions_product_4386 NUMBER(10) NOT NULL,
    promotion_id VARCHAR2(12) NOT NULL,
    product_ids_value VARCHAR2(7) NOT NULL,
    CONSTRAINT pk_col_07_promotions_prod_4dca PRIMARY KEY (promotion_id)
);

-- Table: 08_shipping
-- Rows: 150
CREATE TABLE col_08_shipping (
    shipping_id VARCHAR2(13) NOT NULL,
    order_id VARCHAR2(12) NOT NULL,
    carrier_id VARCHAR2(9) NOT NULL,
    carrier_name VARCHAR2(9) NOT NULL,
    tracking_number VARCHAR2(16) NOT NULL,
    ship_date DATE NOT NULL,
    delivery_date DATE NOT NULL,
    shipping_cost NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_08_shipping PRIMARY KEY (shipping_id)
);

-- Table: 09_payments
-- Rows: 200
CREATE TABLE col_09_payments (
    payment_id VARCHAR2(12) NOT NULL,
    order_id VARCHAR2(12) NOT NULL,
    payment_method_id NUMBER(10) NOT NULL,
    payment_method_name VARCHAR2(19) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    payment_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_09_payments PRIMARY KEY (payment_id)
);

-- Table: 10_categories
-- Rows: 20
CREATE TABLE col_10_categories (
    category_id VARCHAR2(7) NOT NULL,
    category_name VARCHAR2(16) NOT NULL,
    parent_category_id VARCHAR2(7),
    CONSTRAINT pk_col_10_categories PRIMARY KEY (category_id, category_name)
);

-- Table: 10_categories_category_id
-- Rows: 20
CREATE TABLE col_10_categories_category_id (
    category_id VARCHAR2(7) NOT NULL,
    description VARCHAR2(40) NOT NULL,
    CONSTRAINT pk_col_10_categories_cate_b3b4 PRIMARY KEY (category_id)
);

-- Table: 11_employees
-- Rows: 150
CREATE TABLE col_11_employees (
    employee_id VARCHAR2(12) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    department_id VARCHAR2(9) NOT NULL,
    department_name VARCHAR2(15) NOT NULL,
    department_location VARCHAR2(15) NOT NULL,
    job_title VARCHAR2(15) NOT NULL,
    salary NUMBER(15,2) NOT NULL,
    hire_date DATE NOT NULL,
    CONSTRAINT pk_col_11_employees PRIMARY KEY (employee_id)
);

-- Table: 12_employee_skills
-- Rows: 590
CREATE TABLE col_12_employee_skills (
    employee_skill_id VARCHAR2(10) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    skill_id VARCHAR2(12) NOT NULL,
    skill_name VARCHAR2(27) NOT NULL,
    proficiency_level VARCHAR2(18) NOT NULL,
    years_experience NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_12_employee_skills PRIMARY KEY (employee_skill_id)
);

-- Table: 13_projects
-- Rows: 50
CREATE TABLE col_13_projects (
    project_id VARCHAR2(12) NOT NULL,
    project_name VARCHAR2(15) NOT NULL,
    client_id VARCHAR2(13) NOT NULL,
    client_name VARCHAR2(13) NOT NULL,
    client_industry VARCHAR2(19) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget NUMBER(15,2) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_13_projects PRIMARY KEY (project_id)
);

-- Table: 14_project_assignments
-- Rows: 327
CREATE TABLE col_14_project_assignments (
    assignment_id VARCHAR2(16) NOT NULL,
    project_id VARCHAR2(12) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    role VARCHAR2(13) NOT NULL,
    allocation_percent NUMBER(10) NOT NULL,
    start_date DATE NOT NULL,
    CONSTRAINT pk_col_14_project_assignments PRIMARY KEY (assignment_id)
);

-- Table: 15_timesheets
-- Rows: 500
CREATE TABLE col_15_timesheets (
    timesheet_id VARCHAR2(12) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    project_id VARCHAR2(12) NOT NULL,
    work_date DATE NOT NULL,
    hours NUMBER(15,2) NOT NULL,
    task_description VARCHAR2(30) NOT NULL,
    billable NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_15_timesheets PRIMARY KEY (timesheet_id)
);

-- Table: 16_departments
-- Rows: 20
CREATE TABLE col_16_departments (
    department_id VARCHAR2(9) NOT NULL,
    department_name VARCHAR2(15) NOT NULL,
    manager_id VARCHAR2(12) NOT NULL,
    location_id VARCHAR2(7) NOT NULL,
    building VARCHAR2(15) NOT NULL,
    floor NUMBER(10) NOT NULL,
    budget NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_16_departments PRIMARY KEY (department_id)
);

-- Table: 17_performance_reviews
-- Rows: 200
CREATE TABLE col_17_performance_reviews (
    review_id VARCHAR2(12) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    reviewer_id VARCHAR2(12) NOT NULL,
    review_date DATE NOT NULL,
    rating NUMBER(10) NOT NULL,
    comments VARCHAR2(28) NOT NULL,
    goals VARCHAR2(37) NOT NULL,
    CONSTRAINT pk_col_17_performance_reviews PRIMARY KEY (review_id)
);

-- Table: 18_training_courses
-- Rows: 40
CREATE TABLE col_18_training_courses (
    course_id VARCHAR2(13) NOT NULL,
    course_name VARCHAR2(27) NOT NULL,
    provider_id VARCHAR2(9) NOT NULL,
    provider_name VARCHAR2(30) NOT NULL,
    provider_contact VARCHAR2(33) NOT NULL,
    duration_hours NUMBER(10) NOT NULL,
    cost NUMBER(15,2) NOT NULL,
    category VARCHAR2(16) NOT NULL,
    CONSTRAINT pk_col_18_training_courses PRIMARY KEY (course_id)
);

-- Table: 19_training_enrollments
-- Rows: 200
CREATE TABLE col_19_training_enrollments (
    enrollment_id VARCHAR2(16) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    course_id VARCHAR2(13) NOT NULL,
    enrollment_date DATE NOT NULL,
    completion_date DATE,
    score NUMBER(15,2),
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_19_training_enrollments PRIMARY KEY (enrollment_id)
);

-- Table: 20_employee_benefits
-- Rows: 150
CREATE TABLE col_20_employee_benefits (
    benefit_id VARCHAR2(12) NOT NULL,
    employee_id VARCHAR2(12) NOT NULL,
    plan_id VARCHAR2(9) NOT NULL,
    plan_name VARCHAR2(21) NOT NULL,
    plan_provider VARCHAR2(15) NOT NULL,
    monthly_cost NUMBER(15,2) NOT NULL,
    enrollment_date DATE NOT NULL,
    CONSTRAINT pk_col_20_employee_benefits PRIMARY KEY (benefit_id)
);

-- Table: 21_patients
-- Rows: 200
CREATE TABLE col_21_patients (
    patient_id VARCHAR2(12) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR2(7) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    insurance_id VARCHAR2(9) NOT NULL,
    insurance_provider VARCHAR2(18) NOT NULL,
    insurance_plan VARCHAR2(12) NOT NULL,
    address VARCHAR2(21) NOT NULL,
    city VARCHAR2(16) NOT NULL,
    state VARCHAR2(3) NOT NULL,
    zip NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_21_patients PRIMARY KEY (patient_id)
);

-- Table: 22_doctors
-- Rows: 50
CREATE TABLE col_22_doctors (
    doctor_id VARCHAR2(10) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    specialty_id VARCHAR2(9) NOT NULL,
    specialty_name VARCHAR2(25) NOT NULL,
    years_experience NUMBER(10) NOT NULL,
    hospital_id VARCHAR2(9) NOT NULL,
    hospital_name VARCHAR2(15) NOT NULL,
    hospital_city VARCHAR2(12) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    CONSTRAINT pk_col_22_doctors PRIMARY KEY (doctor_id)
);

-- Table: 23_appointments
-- Rows: 400
CREATE TABLE col_23_appointments (
    appointment_id VARCHAR2(15) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    doctor_id VARCHAR2(10) NOT NULL,
    appointment_date DATE NOT NULL,
    duration_minutes NUMBER(10) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    reason VARCHAR2(18) NOT NULL,
    CONSTRAINT pk_col_23_appointments PRIMARY KEY (appointment_id)
);

-- Table: 23_appointments_appointment_time
-- Rows: 800
CREATE TABLE col_23_appointments_appoi_13ed (
    col_23_appointments_appoi_6aee NUMBER(10) NOT NULL,
    appointment_id VARCHAR2(15) NOT NULL,
    appointment_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_23_appointments_ap_13ed PRIMARY KEY (appointment_id)
);

-- Table: 24_prescriptions
-- Rows: 300
CREATE TABLE col_24_prescriptions (
    prescription_id VARCHAR2(12) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    doctor_id VARCHAR2(10) NOT NULL,
    drug_id VARCHAR2(12) NOT NULL,
    drug_name VARCHAR2(19) NOT NULL,
    drug_category VARCHAR2(21) NOT NULL,
    dosage VARCHAR2(7) NOT NULL,
    frequency VARCHAR2(25) NOT NULL,
    duration_days NUMBER(10) NOT NULL,
    date_prescribed DATE NOT NULL,
    CONSTRAINT pk_col_24_prescriptions PRIMARY KEY (prescription_id)
);

-- Table: 25_lab_tests
-- Rows: 250
CREATE TABLE col_25_lab_tests (
    test_id VARCHAR2(15) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    test_type_id VARCHAR2(12) NOT NULL,
    test_name VARCHAR2(22) NOT NULL,
    test_category VARCHAR2(15) NOT NULL,
    order_date DATE NOT NULL,
    result_date DATE NOT NULL,
    result_value NUMBER(15,2) NOT NULL,
    normal_range VARCHAR2(9) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_25_lab_tests PRIMARY KEY (test_id)
);

-- Table: 26_diagnoses
-- Rows: 200
CREATE TABLE col_26_diagnoses (
    diagnosis_id VARCHAR2(12) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    doctor_id VARCHAR2(10) NOT NULL,
    icd_code VARCHAR2(13) NOT NULL,
    diagnosis_name VARCHAR2(19) NOT NULL,
    diagnosis_category VARCHAR2(15) NOT NULL,
    diagnosis_date DATE NOT NULL,
    severity VARCHAR2(12) NOT NULL,
    CONSTRAINT pk_col_26_diagnoses PRIMARY KEY (diagnosis_id)
);

-- Table: 27_treatments
-- Rows: 180
CREATE TABLE col_27_treatments (
    treatment_id VARCHAR2(13) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    doctor_id VARCHAR2(10) NOT NULL,
    procedure_code VARCHAR2(12) NOT NULL,
    procedure_name VARCHAR2(19) NOT NULL,
    procedure_type VARCHAR2(15) NOT NULL,
    treatment_date DATE NOT NULL,
    cost NUMBER(15,2) NOT NULL,
    duration_minutes NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_27_treatments PRIMARY KEY (treatment_id)
);

-- Table: 28_medical_history
-- Rows: 300
CREATE TABLE col_28_medical_history (
    history_id VARCHAR2(15) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    record_date DATE NOT NULL,
    condition VARCHAR2(19) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    notes VARCHAR2(37) NOT NULL,
    CONSTRAINT pk_col_28_medical_history PRIMARY KEY (history_id)
);

-- Table: 29_billing
-- Rows: 250
CREATE TABLE col_29_billing (
    bill_id VARCHAR2(15) NOT NULL,
    patient_id VARCHAR2(12) NOT NULL,
    appointment_id VARCHAR2(15) NOT NULL,
    insurance_id VARCHAR2(9) NOT NULL,
    insurance_provider VARCHAR2(18) NOT NULL,
    total_amount NUMBER(15,2) NOT NULL,
    insurance_covered NUMBER(15,2) NOT NULL,
    patient_responsibility NUMBER(15,2) NOT NULL,
    bill_date DATE NOT NULL,
    payment_status VARCHAR2(21) NOT NULL,
    CONSTRAINT pk_col_29_billing PRIMARY KEY (bill_id)
);

-- Table: 30_hospital_departments
-- Rows: 25
CREATE TABLE col_30_hospital_departments (
    department_id VARCHAR2(9) NOT NULL,
    department_name VARCHAR2(15) NOT NULL,
    hospital_id VARCHAR2(9) NOT NULL,
    hospital_name VARCHAR2(15) NOT NULL,
    building VARCHAR2(15) NOT NULL,
    floor NUMBER(10) NOT NULL,
    beds NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_30_hospital_departments PRIMARY KEY (department_id)
);

-- Table: 31_students
-- Rows: 300
CREATE TABLE col_31_students (
    student_id VARCHAR2(13) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    date_of_birth DATE NOT NULL,
    enrollment_date DATE NOT NULL,
    major_id VARCHAR2(12) NOT NULL,
    major_name VARCHAR2(24) NOT NULL,
    department VARCHAR2(16) NOT NULL,
    gpa NUMBER(15,2) NOT NULL,
    address VARCHAR2(21) NOT NULL,
    city VARCHAR2(16) NOT NULL,
    state VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_31_students PRIMARY KEY (student_id)
);

-- Table: 32_courses
-- Rows: 80
CREATE TABLE col_32_courses (
    course_id VARCHAR2(13) NOT NULL,
    course_code VARCHAR2(7) NOT NULL,
    course_name VARCHAR2(27) NOT NULL,
    instructor_id VARCHAR2(10) NOT NULL,
    instructor_name VARCHAR2(18) NOT NULL,
    instructor_email VARCHAR2(31) NOT NULL,
    department_id VARCHAR2(9) NOT NULL,
    department_name VARCHAR2(15) NOT NULL,
    credits NUMBER(10) NOT NULL,
    semester VARCHAR2(16) NOT NULL,
    max_enrollment NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_32_courses PRIMARY KEY (course_id)
);

-- Table: 33_course_enrollments
-- Rows: 1374
CREATE TABLE col_33_course_enrollments (
    enrollment_id VARCHAR2(16) NOT NULL,
    student_id VARCHAR2(13) NOT NULL,
    course_id VARCHAR2(13) NOT NULL,
    semester VARCHAR2(16) NOT NULL,
    enrollment_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_33_course_enrollments PRIMARY KEY (enrollment_id)
);

-- Table: 34_grades
-- Rows: 800
CREATE TABLE col_34_grades (
    grade_id VARCHAR2(13) NOT NULL,
    enrollment_id VARCHAR2(16) NOT NULL,
    assignment_type VARCHAR2(12) NOT NULL,
    assignment_name VARCHAR2(19) NOT NULL,
    score NUMBER(15,2) NOT NULL,
    max_score NUMBER(10) NOT NULL,
    weight NUMBER(15,2) NOT NULL,
    date_col DATE NOT NULL,
    CONSTRAINT pk_col_34_grades PRIMARY KEY (grade_id)
);

-- Table: 35_faculty
-- Rows: 60
CREATE TABLE col_35_faculty (
    faculty_id VARCHAR2(10) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    department_id VARCHAR2(9) NOT NULL,
    department_name VARCHAR2(15) NOT NULL,
    office_building VARCHAR2(30) NOT NULL,
    office_number NUMBER(10) NOT NULL,
    rank VARCHAR2(28) NOT NULL,
    hire_date DATE NOT NULL,
    salary NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_35_faculty PRIMARY KEY (faculty_id)
);

-- Table: 36_classrooms
-- Rows: 50
CREATE TABLE col_36_classrooms (
    classroom_id VARCHAR2(12) NOT NULL,
    room_number NUMBER(10) NOT NULL,
    building_id VARCHAR2(9) NOT NULL,
    building_name VARCHAR2(30) NOT NULL,
    building_address VARCHAR2(21) NOT NULL,
    capacity NUMBER(10) NOT NULL,
    room_type VARCHAR2(18) NOT NULL,
    has_projector NUMBER(15,2) NOT NULL,
    has_computers NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_col_36_classrooms PRIMARY KEY (classroom_id)
);

-- Table: 37_class_schedules
-- Rows: 120
CREATE TABLE col_37_class_schedules (
    schedule_id VARCHAR2(12) NOT NULL,
    course_id VARCHAR2(13) NOT NULL,
    classroom_id VARCHAR2(12) NOT NULL,
    day_of_week VARCHAR2(13) NOT NULL,
    semester VARCHAR2(16) NOT NULL,
    CONSTRAINT pk_col_37_class_schedules PRIMARY KEY (schedule_id)
);

-- Table: 37_class_schedules_start_time
-- Rows: 240
CREATE TABLE col_37_class_schedules_st_210d (
    col_37_class_schedules_st_0708 NUMBER(10) NOT NULL,
    schedule_id VARCHAR2(12) NOT NULL,
    start_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_37_class_schedules_210d PRIMARY KEY (schedule_id)
);

-- Table: 37_class_schedules_end_time
-- Rows: 240
CREATE TABLE col_37_class_schedules_en_4ea6 (
    col_37_class_schedules_en_c7d1 NUMBER(10) NOT NULL,
    schedule_id VARCHAR2(12) NOT NULL,
    end_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_37_class_schedules_4ea6 PRIMARY KEY (schedule_id)
);

-- Table: 38_attendance
-- Rows: 500
CREATE TABLE col_38_attendance (
    attendance_id VARCHAR2(13) NOT NULL,
    enrollment_id VARCHAR2(16) NOT NULL,
    class_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    notes VARCHAR2(37),
    CONSTRAINT pk_col_38_attendance PRIMARY KEY (attendance_id)
);

-- Table: 39_library_books
-- Rows: 200
CREATE TABLE col_39_library_books (
    book_id VARCHAR2(13) NOT NULL,
    isbn VARCHAR2(21) NOT NULL,
    title VARCHAR2(21) NOT NULL,
    author_id VARCHAR2(12) NOT NULL,
    author_name VARCHAR2(13) NOT NULL,
    author_country VARCHAR2(10) NOT NULL,
    publisher VARCHAR2(16) NOT NULL,
    publication_year NUMBER(10) NOT NULL,
    category VARCHAR2(16) NOT NULL,
    available_copies NUMBER(10) NOT NULL,
    CONSTRAINT pk_col_39_library_books PRIMARY KEY (book_id)
);

-- Table: 40_book_checkouts
-- Rows: 300
CREATE TABLE col_40_book_checkouts (
    checkout_id VARCHAR2(18) NOT NULL,
    book_id VARCHAR2(13) NOT NULL,
    student_id VARCHAR2(13) NOT NULL,
    checkout_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_40_book_checkouts PRIMARY KEY (checkout_id)
);

-- Table: 41_bank_customers
-- Rows: 200
CREATE TABLE col_41_bank_customers (
    customer_id VARCHAR2(12) NOT NULL,
    first_name VARCHAR2(18) NOT NULL,
    last_name VARCHAR2(16) NOT NULL,
    ssn VARCHAR2(16) NOT NULL,
    email VARCHAR2(34) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    branch_id VARCHAR2(13) NOT NULL,
    branch_name VARCHAR2(13) NOT NULL,
    branch_city VARCHAR2(19) NOT NULL,
    branch_state VARCHAR2(3) NOT NULL,
    customer_since DATE NOT NULL,
    customer_type VARCHAR2(15) NOT NULL,
    CONSTRAINT pk_col_41_bank_customers PRIMARY KEY (customer_id)
);

-- Table: 42_bank_accounts
-- Rows: 400
CREATE TABLE col_42_bank_accounts (
    account_id VARCHAR2(16) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    account_type_id NUMBER(10) NOT NULL,
    account_type VARCHAR2(18) NOT NULL,
    account_number NUMBER(10) NOT NULL,
    balance NUMBER(15,2) NOT NULL,
    interest_rate NUMBER(15,2) NOT NULL,
    opened_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_42_bank_accounts PRIMARY KEY (account_id)
);

-- Table: 43_transactions
-- Rows: 1000
CREATE TABLE col_43_transactions (
    transaction_id VARCHAR2(19) NOT NULL,
    account_id VARCHAR2(16) NOT NULL,
    transaction_type VARCHAR2(15) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transaction_date DATE NOT NULL,
    description VARCHAR2(40) NOT NULL,
    balance_after NUMBER(15,2) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_43_transactions PRIMARY KEY (transaction_id)
);

-- Table: 43_transactions_transaction_time
-- Rows: 2000
CREATE TABLE col_43_transactions_trans_a5b3 (
    col_43_transactions_trans_cd44 NUMBER(10) NOT NULL,
    transaction_id VARCHAR2(19) NOT NULL,
    transaction_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_43_transactions_tr_a5b3 PRIMARY KEY (transaction_id)
);

-- Table: 44_loans
-- Rows: 150
CREATE TABLE col_44_loans (
    loan_id VARCHAR2(15) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    loan_type_id NUMBER(10) NOT NULL,
    loan_type VARCHAR2(12) NOT NULL,
    loan_officer_id VARCHAR2(7) NOT NULL,
    loan_officer_name VARCHAR2(22) NOT NULL,
    principal_amount NUMBER(15,2) NOT NULL,
    interest_rate NUMBER(15,2) NOT NULL,
    term_months NUMBER(10) NOT NULL,
    monthly_payment NUMBER(15,2) NOT NULL,
    start_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_44_loans PRIMARY KEY (loan_id)
);

-- Table: 45_loan_payments
-- Rows: 1819
CREATE TABLE col_45_loan_payments (
    payment_id VARCHAR2(12) NOT NULL,
    loan_id VARCHAR2(15) NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    principal_paid NUMBER(15,2) NOT NULL,
    interest_paid NUMBER(15,2) NOT NULL,
    remaining_balance NUMBER(15,2) NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_45_loan_payments PRIMARY KEY (payment_id)
);

-- Table: 46_credit_cards
-- Rows: 250
CREATE TABLE col_46_credit_cards (
    card_id VARCHAR2(15) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    card_number VARCHAR2(28) NOT NULL,
    card_type VARCHAR2(15) NOT NULL,
    credit_limit NUMBER(15,2) NOT NULL,
    current_balance NUMBER(15,2) NOT NULL,
    available_credit NUMBER(15,2) NOT NULL,
    interest_rate NUMBER(15,2) NOT NULL,
    issue_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_46_credit_cards PRIMARY KEY (card_id)
);

-- Table: 47_credit_card_transactions
-- Rows: 600
CREATE TABLE col_47_credit_card_transa_c098 (
    transaction_id VARCHAR2(19) NOT NULL,
    card_id VARCHAR2(15) NOT NULL,
    merchant_id VARCHAR2(15) NOT NULL,
    merchant_name VARCHAR2(18) NOT NULL,
    merchant_category VARCHAR2(15) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    transaction_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_47_credit_card_tra_c098 PRIMARY KEY (transaction_id)
);

-- Table: 47_credit_card_transactions_transaction_time
-- Rows: 1200
CREATE TABLE col_47_credit_card_transa_a060 (
    col_47_credit_card_transa_3ebc NUMBER(10) NOT NULL,
    transaction_id VARCHAR2(19) NOT NULL,
    transaction_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_47_credit_card_tra_a060 PRIMARY KEY (transaction_id)
);

-- Table: 48_investment_portfolios
-- Rows: 100
CREATE TABLE col_48_investment_portfolios (
    portfolio_id VARCHAR2(13) NOT NULL,
    customer_id VARCHAR2(12) NOT NULL,
    account_id VARCHAR2(16) NOT NULL,
    portfolio_type VARCHAR2(15) NOT NULL,
    advisor_id VARCHAR2(9) NOT NULL,
    advisor_name VARCHAR2(15) NOT NULL,
    total_value NUMBER(15,2) NOT NULL,
    created_date DATE NOT NULL,
    risk_level VARCHAR2(22) NOT NULL,
    CONSTRAINT pk_col_48_investment_port_968e PRIMARY KEY (portfolio_id)
);

-- Table: 49_securities_holdings
-- Rows: 1241
CREATE TABLE col_49_securities_holdings (
    holding_id VARCHAR2(15) NOT NULL,
    portfolio_id VARCHAR2(13) NOT NULL,
    security_id VARCHAR2(12) NOT NULL,
    security_symbol VARCHAR2(4) NOT NULL,
    security_name VARCHAR2(18) NOT NULL,
    security_type VARCHAR2(16) NOT NULL,
    shares NUMBER(15,2) NOT NULL,
    purchase_price NUMBER(15,2) NOT NULL,
    current_price NUMBER(15,2) NOT NULL,
    purchase_date DATE NOT NULL,
    CONSTRAINT pk_col_49_securities_holdings PRIMARY KEY (holding_id)
);

-- Table: 50_atm_transactions
-- Rows: 400
CREATE TABLE col_50_atm_transactions (
    atm_transaction_id VARCHAR2(16) NOT NULL,
    account_id VARCHAR2(16) NOT NULL,
    atm_id VARCHAR2(10) NOT NULL,
    atm_location VARCHAR2(16) NOT NULL,
    atm_address VARCHAR2(18) NOT NULL,
    atm_city VARCHAR2(16) NOT NULL,
    transaction_type VARCHAR2(15) NOT NULL,
    amount NUMBER(15,2) NOT NULL,
    fee NUMBER(15,2) NOT NULL,
    transaction_date DATE NOT NULL,
    status VARCHAR2(13) NOT NULL,
    CONSTRAINT pk_col_50_atm_transactions PRIMARY KEY (atm_transaction_id)
);

-- Table: 50_atm_transactions_transaction_time
-- Rows: 800
CREATE TABLE col_50_atm_transactions_t_202e (
    col_50_atm_transactions_t_3d32 NUMBER(10) NOT NULL,
    atm_transaction_id VARCHAR2(16) NOT NULL,
    transaction_time_value VARCHAR2(3) NOT NULL,
    CONSTRAINT pk_col_50_atm_transaction_202e PRIMARY KEY (atm_transaction_id)
);

-- =====================================================
-- FOREIGN KEY constraints
-- =====================================================

ALTER TABLE col_01_products
    ADD CONSTRAINT fk_col_01_products_1
    FOREIGN KEY (category_id)
    REFERENCES col_10_categories(category_id);

ALTER TABLE col_02_orders
    ADD CONSTRAINT fk_col_02_orders_2
    FOREIGN KEY (customer_id)
    REFERENCES col_04_customers(customer_id);

ALTER TABLE col_03_order_items
    ADD CONSTRAINT fk_col_03_order_items_3
    FOREIGN KEY (order_id)
    REFERENCES col_02_orders(order_id);

ALTER TABLE col_03_order_items
    ADD CONSTRAINT fk_col_03_order_items_4
    FOREIGN KEY (product_id)
    REFERENCES col_01_products(product_id);

ALTER TABLE col_05_reviews
    ADD CONSTRAINT fk_col_05_reviews_5
    FOREIGN KEY (product_id)
    REFERENCES col_01_products(product_id);

ALTER TABLE col_05_reviews
    ADD CONSTRAINT fk_col_05_reviews_6
    FOREIGN KEY (customer_id)
    REFERENCES col_04_customers(customer_id);

ALTER TABLE col_06_inventory
    ADD CONSTRAINT fk_col_06_inventory_7
    FOREIGN KEY (product_id)
    REFERENCES col_01_products(product_id);

ALTER TABLE col_09_payments
    ADD CONSTRAINT fk_col_09_payments_8
    FOREIGN KEY (order_id)
    REFERENCES col_02_orders(order_id);

ALTER TABLE col_11_employees
    ADD CONSTRAINT fk_col_11_employees_9
    FOREIGN KEY (department_id)
    REFERENCES col_16_departments(department_id);

ALTER TABLE col_12_employee_skills
    ADD CONSTRAINT fk_col_12_employee_skills_10
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_14_project_assignments
    ADD CONSTRAINT fk_col_14_project_assig_8d23
    FOREIGN KEY (project_id)
    REFERENCES col_13_projects(project_id);

ALTER TABLE col_14_project_assignments
    ADD CONSTRAINT fk_col_14_project_assig_997f
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_15_timesheets
    ADD CONSTRAINT fk_col_15_timesheets_13
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_15_timesheets
    ADD CONSTRAINT fk_col_15_timesheets_14
    FOREIGN KEY (project_id)
    REFERENCES col_13_projects(project_id);

ALTER TABLE col_17_performance_reviews
    ADD CONSTRAINT fk_col_17_performance_r_9dd7
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_17_performance_reviews
    ADD CONSTRAINT fk_col_17_performance_r_800d
    FOREIGN KEY (reviewer_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_19_training_enrollments
    ADD CONSTRAINT fk_col_19_training_enro_ad53
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_19_training_enrollments
    ADD CONSTRAINT fk_col_19_training_enro_e7fa
    FOREIGN KEY (course_id)
    REFERENCES col_18_training_courses(course_id);

ALTER TABLE col_20_employee_benefits
    ADD CONSTRAINT fk_col_20_employee_benefits_19
    FOREIGN KEY (employee_id)
    REFERENCES col_11_employees(employee_id);

ALTER TABLE col_23_appointments
    ADD CONSTRAINT fk_col_23_appointments_20
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_23_appointments
    ADD CONSTRAINT fk_col_23_appointments_21
    FOREIGN KEY (doctor_id)
    REFERENCES col_22_doctors(doctor_id);

ALTER TABLE col_24_prescriptions
    ADD CONSTRAINT fk_col_24_prescriptions_22
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_24_prescriptions
    ADD CONSTRAINT fk_col_24_prescriptions_23
    FOREIGN KEY (doctor_id)
    REFERENCES col_22_doctors(doctor_id);

ALTER TABLE col_25_lab_tests
    ADD CONSTRAINT fk_col_25_lab_tests_24
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_26_diagnoses
    ADD CONSTRAINT fk_col_26_diagnoses_25
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_26_diagnoses
    ADD CONSTRAINT fk_col_26_diagnoses_26
    FOREIGN KEY (doctor_id)
    REFERENCES col_22_doctors(doctor_id);

ALTER TABLE col_27_treatments
    ADD CONSTRAINT fk_col_27_treatments_27
    FOREIGN KEY (doctor_id)
    REFERENCES col_22_doctors(doctor_id);

ALTER TABLE col_28_medical_history
    ADD CONSTRAINT fk_col_28_medical_history_28
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_29_billing
    ADD CONSTRAINT fk_col_29_billing_29
    FOREIGN KEY (patient_id)
    REFERENCES col_21_patients(patient_id);

ALTER TABLE col_32_courses
    ADD CONSTRAINT fk_col_32_courses_30
    FOREIGN KEY (department_id)
    REFERENCES col_16_departments(department_id);

ALTER TABLE col_33_course_enrollments
    ADD CONSTRAINT fk_col_33_course_enroll_995a
    FOREIGN KEY (student_id)
    REFERENCES col_31_students(student_id);

ALTER TABLE col_33_course_enrollments
    ADD CONSTRAINT fk_col_33_course_enroll_84cb
    FOREIGN KEY (course_id)
    REFERENCES col_32_courses(course_id);

ALTER TABLE col_35_faculty
    ADD CONSTRAINT fk_col_35_faculty_33
    FOREIGN KEY (department_id)
    REFERENCES col_16_departments(department_id);

ALTER TABLE col_37_class_schedules
    ADD CONSTRAINT fk_col_37_class_schedules_34
    FOREIGN KEY (course_id)
    REFERENCES col_32_courses(course_id);

ALTER TABLE col_37_class_schedules
    ADD CONSTRAINT fk_col_37_class_schedules_35
    FOREIGN KEY (classroom_id)
    REFERENCES col_36_classrooms(classroom_id);

ALTER TABLE col_40_book_checkouts
    ADD CONSTRAINT fk_col_40_book_checkouts_36
    FOREIGN KEY (book_id)
    REFERENCES col_39_library_books(book_id);

ALTER TABLE col_40_book_checkouts
    ADD CONSTRAINT fk_col_40_book_checkouts_37
    FOREIGN KEY (student_id)
    REFERENCES col_31_students(student_id);

ALTER TABLE col_42_bank_accounts
    ADD CONSTRAINT fk_col_42_bank_accounts_38
    FOREIGN KEY (customer_id)
    REFERENCES col_41_bank_customers(customer_id);

ALTER TABLE col_43_transactions
    ADD CONSTRAINT fk_col_43_transactions_39
    FOREIGN KEY (account_id)
    REFERENCES col_42_bank_accounts(account_id);

ALTER TABLE col_45_loan_payments
    ADD CONSTRAINT fk_col_45_loan_payments_40
    FOREIGN KEY (loan_id)
    REFERENCES col_44_loans(loan_id);

ALTER TABLE col_46_credit_cards
    ADD CONSTRAINT fk_col_46_credit_cards_41
    FOREIGN KEY (customer_id)
    REFERENCES col_41_bank_customers(customer_id);

ALTER TABLE col_47_credit_card_transa_c098
    ADD CONSTRAINT fk_col_47_credit_card_t_b424
    FOREIGN KEY (card_id)
    REFERENCES col_46_credit_cards(card_id);

ALTER TABLE col_49_securities_holdings
    ADD CONSTRAINT fk_col_49_securities_ho_2a96
    FOREIGN KEY (portfolio_id)
    REFERENCES col_48_investment_portfolios(portfolio_id);

ALTER TABLE col_50_atm_transactions
    ADD CONSTRAINT fk_col_50_atm_transactions_44
    FOREIGN KEY (account_id)
    REFERENCES col_42_bank_accounts(account_id);

-- =====================================================
-- CREATE INDEX statements
-- =====================================================

CREATE INDEX idx_col_01_products_1 ON col_01_products(category_id);

CREATE INDEX idx_col_02_orders_2 ON col_02_orders(customer_id);

CREATE INDEX idx_col_03_order_items_3 ON col_03_order_items(order_id);

CREATE INDEX idx_col_03_order_items_4 ON col_03_order_items(product_id);

CREATE INDEX idx_col_05_reviews_5 ON col_05_reviews(product_id);

CREATE INDEX idx_col_05_reviews_6 ON col_05_reviews(customer_id);

CREATE INDEX idx_col_06_inventory_7 ON col_06_inventory(product_id);

CREATE INDEX idx_col_09_payments_8 ON col_09_payments(order_id);

CREATE INDEX idx_col_11_employees_9 ON col_11_employees(department_id);

CREATE INDEX idx_col_12_employee_skills_10 ON col_12_employee_skills(employee_id);

CREATE INDEX idx_col_14_project_assign_ced6 ON col_14_project_assignments(project_id);

CREATE INDEX idx_col_14_project_assign_2028 ON col_14_project_assignments(employee_id);

CREATE INDEX idx_col_15_timesheets_13 ON col_15_timesheets(employee_id);

CREATE INDEX idx_col_15_timesheets_14 ON col_15_timesheets(project_id);

CREATE INDEX idx_col_17_performance_re_2259 ON col_17_performance_reviews(employee_id);

CREATE INDEX idx_col_17_performance_re_cb60 ON col_17_performance_reviews(reviewer_id);

CREATE INDEX idx_col_19_training_enrol_b402 ON col_19_training_enrollments(employee_id);

CREATE INDEX idx_col_19_training_enrol_f60a ON col_19_training_enrollments(course_id);

CREATE INDEX idx_col_20_employee_benef_ced7 ON col_20_employee_benefits(employee_id);

CREATE INDEX idx_col_23_appointments_20 ON col_23_appointments(patient_id);

CREATE INDEX idx_col_23_appointments_21 ON col_23_appointments(doctor_id);

CREATE INDEX idx_col_24_prescriptions_22 ON col_24_prescriptions(patient_id);

CREATE INDEX idx_col_24_prescriptions_23 ON col_24_prescriptions(doctor_id);

CREATE INDEX idx_col_25_lab_tests_24 ON col_25_lab_tests(patient_id);

CREATE INDEX idx_col_26_diagnoses_25 ON col_26_diagnoses(patient_id);

CREATE INDEX idx_col_26_diagnoses_26 ON col_26_diagnoses(doctor_id);

CREATE INDEX idx_col_27_treatments_27 ON col_27_treatments(doctor_id);

CREATE INDEX idx_col_28_medical_history_28 ON col_28_medical_history(patient_id);

CREATE INDEX idx_col_29_billing_29 ON col_29_billing(patient_id);

CREATE INDEX idx_col_32_courses_30 ON col_32_courses(department_id);

CREATE INDEX idx_col_33_course_enrollm_5219 ON col_33_course_enrollments(student_id);

CREATE INDEX idx_col_33_course_enrollm_c0ca ON col_33_course_enrollments(course_id);

CREATE INDEX idx_col_35_faculty_33 ON col_35_faculty(department_id);

CREATE INDEX idx_col_37_class_schedules_34 ON col_37_class_schedules(course_id);

CREATE INDEX idx_col_37_class_schedules_35 ON col_37_class_schedules(classroom_id);

CREATE INDEX idx_col_40_book_checkouts_36 ON col_40_book_checkouts(book_id);

CREATE INDEX idx_col_40_book_checkouts_37 ON col_40_book_checkouts(student_id);

CREATE INDEX idx_col_42_bank_accounts_38 ON col_42_bank_accounts(customer_id);

CREATE INDEX idx_col_43_transactions_39 ON col_43_transactions(account_id);

CREATE INDEX idx_col_45_loan_payments_40 ON col_45_loan_payments(loan_id);

CREATE INDEX idx_col_46_credit_cards_41 ON col_46_credit_cards(customer_id);

CREATE INDEX idx_col_47_credit_card_tr_1d06 ON col_47_credit_card_transa_c098(card_id);

CREATE INDEX idx_col_49_securities_hol_d5d3 ON col_49_securities_holdings(portfolio_id);

CREATE INDEX idx_col_50_atm_transactions_44 ON col_50_atm_transactions(account_id);

-- =====================================================
COMMIT;
-- =====================================================