-- =====================================================
-- Auto-generated 3NF Normalized Database Schema
-- Generated by: Automated 3NF Data Modeling System
-- =====================================================

-- Drop existing tables (if any)
-- Execute these statements if you need to recreate the schema

-- DROP TABLE products_tags CASCADE CONSTRAINTS;
-- DROP TABLE products_supplier_contact_ref CASCADE CONSTRAINTS;
-- DROP TABLE products_supplier_ref CASCADE CONSTRAINTS;
-- DROP TABLE products CASCADE CONSTRAINTS;
-- DROP TABLE order_items_supplier_ref CASCADE CONSTRAINTS;
-- DROP TABLE order_items_product_name_ref CASCADE CONSTRAINTS;
-- DROP TABLE order_items_product_id_ref CASCADE CONSTRAINTS;
-- DROP TABLE order_items_order_id_ref CASCADE CONSTRAINTS;
-- DROP TABLE order_items CASCADE CONSTRAINTS;
-- DROP TABLE orders_shipping_address CASCADE CONSTRAINTS;
-- DROP TABLE orders CASCADE CONSTRAINTS;
-- DROP TABLE employees_skills CASCADE CONSTRAINTS;
-- DROP TABLE employees_office_location_ref CASCADE CONSTRAINTS;
-- DROP TABLE employees_department_ref CASCADE CONSTRAINTS;
-- DROP TABLE employees CASCADE CONSTRAINTS;
-- DROP TABLE customers_state_ref CASCADE CONSTRAINTS;
-- DROP TABLE customers CASCADE CONSTRAINTS;

-- =====================================================
-- CREATE TABLE statements
-- =====================================================

-- Table: customers
-- Rows: 10
CREATE TABLE customers (
    customer_id NUMBER(10) NOT NULL,
    customer_name VARCHAR2(21) NOT NULL,
    email VARCHAR2(31) NOT NULL,
    phone VARCHAR2(12) NOT NULL,
    city VARCHAR2(18) NOT NULL,
    state VARCHAR2(3) NOT NULL,
    loyalty_points NUMBER(10) NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

-- Table: customers_state_ref
-- Rows: 6
CREATE TABLE customers_state_ref (
    customers_state_ref_id NUMBER(10) NOT NULL,
    state VARCHAR2(3) NOT NULL,
    country VARCHAR2(4) NOT NULL,
    CONSTRAINT pk_customers_state_ref PRIMARY KEY (customers_state_ref_id)
);

-- Table: employees
-- Rows: 10
CREATE TABLE employees (
    employee_id NUMBER(10) NOT NULL,
    employee_name VARCHAR2(25) NOT NULL,
    manager_id NUMBER(15,2),
    salary NUMBER(10) NOT NULL,
    hire_date DATE NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id)
);

-- Table: employees_department_ref
-- Rows: 5
CREATE TABLE employees_department_ref (
    employees_department_ref_id NUMBER(10) NOT NULL,
    department VARCHAR2(16) NOT NULL,
    office_location VARCHAR2(30) NOT NULL,
    CONSTRAINT pk_employees_department_ref PRIMARY KEY (employees_department_ref_id)
);

-- Table: employees_office_location_ref
-- Rows: 5
CREATE TABLE employees_office_location_ref (
    employees_office_location_ref_ NUMBER(10) NOT NULL,
    office_location VARCHAR2(30) NOT NULL,
    department VARCHAR2(16) NOT NULL,
    CONSTRAINT pk_employees_office_location_ref PRIMARY KEY (employees_office_location_ref_)
);

-- Table: employees_skills
-- Rows: 28
CREATE TABLE employees_skills (
    employees_skills_id NUMBER(10) NOT NULL,
    employee_id NUMBER(10) NOT NULL,
    skills_value VARCHAR2(27) NOT NULL,
    CONSTRAINT pk_employees_skills PRIMARY KEY (employee_id)
);

-- Table: orders
-- Rows: 15
CREATE TABLE orders (
    order_id NUMBER(10) NOT NULL,
    customer_id NUMBER(10) NOT NULL,
    order_date DATE NOT NULL,
    total_amount NUMBER(15,2) NOT NULL,
    payment_method VARCHAR2(16) NOT NULL,
    status VARCHAR2(15) NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

-- Table: orders_shipping_address
-- Rows: 45
CREATE TABLE orders_shipping_address (
    orders_shipping_address_id NUMBER(10) NOT NULL,
    order_id NUMBER(10) NOT NULL,
    shipping_address_value VARCHAR2(21) NOT NULL,
    CONSTRAINT pk_orders_shipping_address PRIMARY KEY (order_id)
);

-- Table: order_items
-- Rows: 22
CREATE TABLE order_items (
    item_id NUMBER(10) NOT NULL,
    order_id NUMBER(10) NOT NULL,
    quantity NUMBER(10) NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (item_id)
);

-- Table: order_items_order_id_ref
-- Rows: 15
CREATE TABLE order_items_order_id_ref (
    order_items_order_id_ref_id NUMBER(10) NOT NULL,
    order_id NUMBER(10) NOT NULL,
    category VARCHAR2(16) NOT NULL,
    CONSTRAINT pk_order_items_order_id_ref PRIMARY KEY (order_items_order_id_ref_id)
);

-- Table: order_items_product_id_ref
-- Rows: 20
CREATE TABLE order_items_product_id_ref (
    order_items_product_id_ref_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    supplier VARCHAR2(21) NOT NULL,
    CONSTRAINT pk_order_items_product_id_ref PRIMARY KEY (order_items_product_id_ref_id)
);

-- Table: order_items_product_name_ref
-- Rows: 20
CREATE TABLE order_items_product_name_ref (
    order_items_product_name_ref_i NUMBER(10) NOT NULL,
    product_name VARCHAR2(24) NOT NULL,
    supplier VARCHAR2(21) NOT NULL,
    CONSTRAINT pk_order_items_product_name_ref PRIMARY KEY (order_items_product_name_ref_i)
);

-- Table: order_items_supplier_ref
-- Rows: 8
CREATE TABLE order_items_supplier_ref (
    order_items_supplier_ref_id NUMBER(10) NOT NULL,
    supplier VARCHAR2(21) NOT NULL,
    category VARCHAR2(16) NOT NULL,
    CONSTRAINT pk_order_items_supplier_ref PRIMARY KEY (order_items_supplier_ref_id)
);

-- Table: products
-- Rows: 10
CREATE TABLE products (
    product_id NUMBER(10) NOT NULL,
    product_name VARCHAR2(24) NOT NULL,
    price NUMBER(15,2) NOT NULL,
    stock_quantity NUMBER(10) NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

-- Table: products_supplier_ref
-- Rows: 5
CREATE TABLE products_supplier_ref (
    products_supplier_ref_id NUMBER(10) NOT NULL,
    supplier VARCHAR2(21) NOT NULL,
    supplier_contact VARCHAR2(31) NOT NULL,
    CONSTRAINT pk_products_supplier_ref PRIMARY KEY (products_supplier_ref_id)
);

-- Table: products_supplier_contact_ref
-- Rows: 5
CREATE TABLE products_supplier_contact_ref (
    products_supplier_contact_ref_ NUMBER(10) NOT NULL,
    supplier_contact VARCHAR2(31) NOT NULL,
    supplier VARCHAR2(21) NOT NULL,
    CONSTRAINT pk_products_supplier_contact_ref PRIMARY KEY (products_supplier_contact_ref_)
);

-- Table: products_tags
-- Rows: 26
CREATE TABLE products_tags (
    products_tags_id NUMBER(10) NOT NULL,
    product_id NUMBER(10) NOT NULL,
    tags_value VARCHAR2(22) NOT NULL,
    CONSTRAINT pk_products_tags PRIMARY KEY (product_id)
);

-- =====================================================
-- FOREIGN KEY constraints
-- =====================================================

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_1
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_2
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id);

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_3
    FOREIGN KEY (customer_id)
    REFERENCES orders(customer_id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_4
    FOREIGN KEY (order_id)
    REFERENCES order_items(order_id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_5
    FOREIGN KEY (product_id)
    REFERENCES order_items_product_id_ref(product_id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_6
    FOREIGN KEY (product_name)
    REFERENCES order_items_product_name_ref(product_name);

ALTER TABLE order_items_product_id_ref
    ADD CONSTRAINT fk_7
    FOREIGN KEY (product_id)
    REFERENCES products(product_id);

ALTER TABLE products_supplier_ref
    ADD CONSTRAINT fk_products_supplier_ref_8
    FOREIGN KEY (supplier)
    REFERENCES order_items_product_id_ref(supplier);

ALTER TABLE employees
    ADD CONSTRAINT fk_employees_9
    FOREIGN KEY (employee_id)
    REFERENCES order_items(item_id);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_10
    FOREIGN KEY (quantity)
    REFERENCES customers(customer_id);

ALTER TABLE order_items_product_name_ref
    ADD CONSTRAINT fk_11
    FOREIGN KEY (product_name)
    REFERENCES products(product_name);

ALTER TABLE order_items_product_id_ref
    ADD CONSTRAINT fk_12
    FOREIGN KEY (supplier)
    REFERENCES products_supplier_ref(supplier);

ALTER TABLE order_items
    ADD CONSTRAINT fk_order_items_13
    FOREIGN KEY (item_id)
    REFERENCES customers(customer_id);

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_14
    FOREIGN KEY (customer_name)
    REFERENCES orders(customer_id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_15
    FOREIGN KEY (order_date)
    REFERENCES order_items(order_id);

-- =====================================================
-- CREATE INDEX statements
-- =====================================================

CREATE INDEX idx_orders_1 ON orders(customer_id);

CREATE INDEX idx_order_items_2 ON order_items(order_id);

CREATE INDEX idx_customers_3 ON customers(customer_id);

CREATE INDEX idx_orders_4 ON orders(order_id);

CREATE INDEX idx_products_5 ON products(product_id);

CREATE INDEX idx_products_6 ON products(product_name);

CREATE INDEX idx_7 ON order_items_product_id_ref(product_id);

CREATE INDEX idx_products_supplier_ref_8 ON products_supplier_ref(supplier);

CREATE INDEX idx_employees_9 ON employees(employee_id);

CREATE INDEX idx_order_items_10 ON order_items(quantity);

CREATE INDEX idx_11 ON order_items_product_name_ref(product_name);

CREATE INDEX idx_12 ON order_items_order_id_ref(category);

CREATE INDEX idx_13 ON order_items_product_id_ref(supplier);

CREATE INDEX idx_order_items_14 ON order_items(item_id);

CREATE INDEX idx_products_15 ON products(price);

CREATE INDEX idx_customers_16 ON customers(customer_name);

CREATE INDEX idx_orders_17 ON orders(order_date);

-- =====================================================
COMMIT;
-- =====================================================